### ISSUE TITLE
IndexError: index 13 is out of bounds for axis 0 with size 4

### ISSUE THREAD

**Issue by PiscesDream** [we0091234/yolov7_plate#2]
hello! 为什莫会出现这样的错误？我的是3分类，为什莫index会出现13。
Traceback (most recent call last):
  File "test.py", line 397, in <module>
    test(opt.data,
  File "test.py", line 236, in test
    confusion_matrix.process_batch(predn, torch.cat((labels[:, 0:1], tbox), 1))
  File "/root/yolo/yolov7_plate/utils/metrics.py", line 148, in process_batch
    self.matrix[detection_classes[m1[j]], gc] += 1  # correct
IndexError: index 13 is out of bounds for axis 0 with size 4

**Comment by we0091234** [comment]
是不是最后一个epoch出现的

**Comment by PiscesDream** [comment]
单独跑test.py这个脚本出现的，训练时是最后出现的

**Comment by we0091234** [comment]
> 单独跑test.py这个脚本出现的，训练时是最后出现的

test.py 我还没改，你是要跑指标，结果吗？

**Comment by PiscesDream** [comment]
对，目前在绘制混淆矩阵会出现这个错误，其他暂无影响

**Comment by we0091234** [comment]
> 

我改了一下，可以跑通，但是我两类，输出只有一类，奇怪
![tmp699A](https://user-images.githubusercontent.com/29919617/206655689-83857503-7f4a-4bde-8a80-8fc6d7f1c792.png)

**Comment by we0091234** [comment]
> 对，目前在绘制混淆矩阵会出现这个错误，其他暂无影响

问题解决了，你重新拉取一下代码就可以了
